export const mockTasks = [
  {
    id: '1',
    title: 'Implementar autenticação JWT',
    description: 'Criar sistema de login e registro com tokens JWT, incluindo refresh token e proteção de rotas.',
    status: 'concluida',
    priority: 'alta',
    category: 'Backend',
    createdAt: '2025-02-01T10:00:00',
    completedAt: '2025-02-05T14:30:00',
    dueDate: '2025-02-10',
  },
  {
    id: '2',
    title: 'Criar dashboard de métricas',
    description: 'Desenvolver página de dashboard com gráficos de produtividade, cards de estatísticas e atividades recentes.',
    status: 'em_progresso',
    priority: 'alta',
    category: 'Frontend',
    createdAt: '2025-02-03T09:00:00',
    completedAt: null,
    dueDate: '2025-02-15',
  },
  {
    id: '3',
    title: 'Modelar banco de dados',
    description: 'Criar diagrama ER e implementar migrations para as tabelas de usuários, tarefas e categorias.',
    status: 'concluida',
    priority: 'media',
    category: 'Backend',
    createdAt: '2025-01-28T08:00:00',
    completedAt: '2025-02-02T16:00:00',
    dueDate: '2025-02-05',
  },
  {
    id: '4',
    title: 'Configurar CI/CD pipeline',
    description: 'Configurar GitHub Actions para testes automáticos, build e deploy automático na Vercel.',
    status: 'pendente',
    priority: 'media',
    category: 'DevOps',
    createdAt: '2025-02-10T11:00:00',
    completedAt: null,
    dueDate: '2025-02-20',
  },
  {
    id: '5',
    title: 'Escrever testes unitários',
    description: 'Implementar testes para os componentes principais usando Jest e React Testing Library.',
    status: 'pendente',
    priority: 'media',
    category: 'Testes',
    createdAt: '2025-02-08T14:00:00',
    completedAt: null,
    dueDate: '2025-02-25',
  },
  {
    id: '6',
    title: 'Refatorar componente de formulário',
    description: 'Extrair lógica de validação para custom hook e melhorar acessibilidade do formulário.',
    status: 'em_progresso',
    priority: 'baixa',
    category: 'Frontend',
    createdAt: '2025-02-07T10:00:00',
    completedAt: null,
    dueDate: '2025-02-18',
  },
  {
    id: '7',
    title: 'Implementar sistema de notificações',
    description: 'Criar componente de toast notifications para feedback de ações do usuário.',
    status: 'pendente',
    priority: 'baixa',
    category: 'Frontend',
    createdAt: '2025-02-12T09:00:00',
    completedAt: null,
    dueDate: '2025-02-28',
  },
  {
    id: '8',
    title: 'Otimizar performance da listagem',
    description: 'Implementar virtualização de lista e lazy loading para melhorar performance com muitos itens.',
    status: 'pendente',
    priority: 'alta',
    category: 'Frontend',
    createdAt: '2025-02-11T15:00:00',
    completedAt: null,
    dueDate: '2025-02-22',
  },
  {
    id: '9',
    title: 'Documentar API REST',
    description: 'Criar documentação completa da API usando Swagger/OpenAPI com exemplos de requisições.',
    status: 'concluida',
    priority: 'media',
    category: 'Documentação',
    createdAt: '2025-01-30T08:00:00',
    completedAt: '2025-02-04T12:00:00',
    dueDate: '2025-02-08',
  },
  {
    id: '10',
    title: 'Criar página de perfil do usuário',
    description: 'Desenvolver página de perfil com edição de dados pessoais, foto e preferências.',
    status: 'em_progresso',
    priority: 'media',
    category: 'Frontend',
    createdAt: '2025-02-09T13:00:00',
    completedAt: null,
    dueDate: '2025-02-19',
  },
]

export const categories = ['Frontend', 'Backend', 'DevOps', 'Testes', 'Documentação', 'Design']

export const mockUser = {
  name: 'Desenvolvedor',
  email: 'admin@taskflow.com',
  avatar: null,
}

export const weeklyData = [
  { name: 'Seg', concluidas: 3, criadas: 2 },
  { name: 'Ter', concluidas: 1, criadas: 4 },
  { name: 'Qua', concluidas: 4, criadas: 1 },
  { name: 'Qui', concluidas: 2, criadas: 3 },
  { name: 'Sex', concluidas: 5, criadas: 2 },
  { name: 'Sáb', concluidas: 1, criadas: 0 },
  { name: 'Dom', concluidas: 0, criadas: 1 },
]

export const monthlyData = [
  { name: 'Jan', concluidas: 18, criadas: 22 },
  { name: 'Fev', concluidas: 12, criadas: 15 },
]
